### ISSUE TITLE
\pagecolor and lualatex-dev give a black page color

### ISSUE THREAD

**Issue by dbitouze** [ho-tex/luacolor#5]
(For what it is worth.) When compiled with `lualatex-dev` (LuaHBTeX, Version 1.13.2), the following MCE gives a black page color.
```latex
\documentclass{article}
\usepackage{luacolor}
\pagecolor{white}
\begin{document}
Foo.
\end{document}
```
Here is the file list:
```
 *File List*
 article.cls    2021/02/12 v1.4n Standard LaTeX document class
  size10.clo    2021/02/12 v1.4n Standard LaTeX file (size option)
luacolor.sty    2021-02-17 v1.17 Color support via LuaTeX's attributes (HO)
   color.sty    2020/02/24 v1.2b Standard LaTeX Color (DPC)
   color.cfg    2016/01/02 v1.6 sample color configuration
  luatex.def    2020/10/05 v1.2a Graphics/color driver for luatex
l3backend-luatex.def    2021-05-07 L3 backend support: PDF output (LuaTeX)
  ts1cmr.fd    2019/12/16 v2.5j Standard LaTeX font definitions
supp-pdf.mkii
 ***********
```

**Comment by u-fischer** [comment]
Oh well, you correct one thing and the next breaks. luacolor is now able to color also things in the background hooks, and this means that it also colors the pagecolor rectangle, and naturally in black as its color is not set with attributes. I guess we will need some abstraction for `\pdfextension colorstack\@pdfcolorstack push{\current@page@color}%` in luatex.def so that luacolor can redefine it.
